/**:
  ros__parameters:
    network:
      config: "$(find-pkg-share op3_vision_darknet)/config/reality-v0.1/reality.cfg"
      weights: "$(find-pkg-share op3_vision_darknet)/config/reality-v0.1/reality_best.weights"
      class_names: "$(find-pkg-share op3_vision_darknet)/config/reality-v0.1/reality.names"
    detection:
      threshold: 0.5
      nms_threshold: 0.45
