/**:
  ros__parameters:
    network:
      config: "$(find-pkg-share bh_vision)/config/bh-network/bh-v10.cfg"
      weights: "$(find-pkg-share bh_vision)/config/bh-network/bh-v10-custom_last.weights"
      class_names: "$(find-pkg-share bh_vision)/config/bh-network/class.names"
    detection:
      threshold: 0.5
      nms_threshold: 0.45
